### PR TITLE
Add clang-tidy

### LINKED ISSUE #37: Add clang-tidy config
# 🚀 Feature Request

Add a clang-tidy configuration file, like we did for the clang-format

### PR DESCRIPTION
**Pull request by matthew-reynolds**
# Pull Request

Closes #37. Adds a `clang-tidy` config file, as well as a wrapper to easily use `clang-tidy` in a catkin workspace. Default behaviour is to generate a file for each package of the requested changes in `workspace/clang-tidy-fixes`. For example, `workspace/clang-tidy-fixes/package1_fixes`. If the `-f` option is specified, the tool will automatically attempt to fix the issues it encounters. This behaviour is not the default since although `clang-tidy` is great at finding and describing errors, it can often do a poor job of fixing issues itself.

~TODO: Still need to add ability to blacklist/whitelist packages, since currently all packages in the workspace will be tidied.~
Added in d85d37b. Syntax: `run_clang_tidy.py [packages...]`. If no packages are specified, all packages in the workspace are tidied. Is able to handle metapackages.

~TODO: Need to add `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` and maybe  `-DCMAKE_CXX_CLANG_TIDY=clang-tidy-7` to catkin config~
Added in b8144ad

Full help text:
```
usage: run_clang_tidy.py [-h] [-f] [-j JOBS] [-q] [-v]
                         [packages [packages ...]]

Wrapper for running clang-tidy on a catkin workspace.

positional arguments:
  packages              List of packages to tidy

optional arguments:
  -h, --help            show this help message and exit
  -f, --fix             Attempt to automatically fix issues
  -j JOBS, --jobs JOBS  Number of packages to tidy concurrently (default=4)
  -q, --quiet           Do not produce any stdout output
  -v, --verbose         Output generated changefiles to stdout

Note: In order for clang-tidy to understand which files to tidy, the workspace
must be built with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON.
```

## Contribution Checklist

- [x] I have read the [contributing](https://github.com/uwreact/frc_control/blob/melodic-devel/CONTRIBUTING.md) guide.
- [x] I have referenced relevant issues.
- [x] I have labeled accordingly.
- [x] I have detailed my changes as much as possible.

## Change Checklist

- [ ] I have added tests.
- [x] I have added necessary documentation.
- [x] I have auto formatted using clang-format or yapf.

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
Added ability to specify packages, updated description

**Comment by matthew-reynolds** [comment]
Improved tool description, added compiler options to default catkin configs

**Comment by matthew-reynolds** [comment]
@michaelwm @wmmc88 Ready for review

**Review by ghost — APPROVED** [review]
Looks good

**Pull request merged**
