### PR TITLE
Update C++03 packages to C++14

### PR DESCRIPTION
**Pull request by matthew-reynolds**
# Pull Request

Now that we're on Melodic, the default C++ standard is C++14, rather than C++03 in Kinetic. This PR just updates a few small things to bring the packages up to modern C++.

(I know `#pragma once` isn't standard and isn't part of C++11 or 14, but it's pretty fair to lump it with modern C++)

## Contribution Checklist

- [x] I have read the [contributing](https://github.com/uwreact/frc_control/blob/melodic-devel/CONTRIBUTING.md) guide.
- [ ] I have referenced relevant issues.
- [x] I have labeled accordingly.
- [x] I have detailed my changes as much as possible.

## Change Checklist

- [ ] I have added tests.
- [x] I have added necessary documentation.
- [x] I have auto formatted using clang-format or yapf.

### CODE REVIEW

**Comment by wmmc88** [comment]
Travis failing on clang format

**Comment by matthew-reynolds** [comment]
Updated - Apologies for slow turnaround.

**Review by wmmc88 — APPROVED** [review]

**Comment by wmmc88** [comment]
Because pragma once is not standard, should we keep the include guards just in case? Supposedly g++ does the same optimization when include guards are detected.

**Comment by matthew-reynolds** [comment]
You're right, these days most compilers (At least GCC) are smart enough to perform the same optimizations with include guards and pragma once.

Pragma once is supported by every worthwhile compiler and is easier to maintain, I would prefer to keep it unless there are compelling arguments otherwise. The biggest one people point out is that including the same file from different relative paths can cause issues in some cases, but that isn't really a concern the way Catkin does things - We always `#include <package_name/header.h>` rather than using relative paths.

(Also I'm pretty sure a lot of ROS pkgs use `#pragma once` so if we're worried about portability I think we're toast anyways.)

**Pull request merged**
